### ISSUE TITLE
Bridge is throwing exception for NServiceBus v7 beta12

### ISSUE THREAD

**Issue by SeanFeldman** [SzymonPobiega/NServiceBus.Bridge#15]
```
System.Collections.Generic.KeyNotFoundException: 'The given key 
(NServiceBus.StartupDiagnosticEntries) was not present in the dictionary.'
```

Looking at the stacktrace, `MsmqTransportInfrastructure` is the one that fails when invoked by `NServiceBus.Raw`.

<details><summary> exception
</summary>

   at NServiceBus.Settings.SettingsHolder.Get(String key)
   at NServiceBus.Settings.SettingsHolder.Get[T]()
   at NServiceBus.DiagnosticSettingsExtensions.AddStartupDiagnosticsSection(ReadOnlySettings settings, String sectionName, Object section)
   at NServiceBus.Transport.Msmq.MsmqTransportInfrastructure.Start()
   at NServiceBus.Raw.StartableRawEndpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bridge`2.<Start>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\github\nsb\docs.particular.net\samples\azure\azure-service-bus-msmq-bridge\ASB_8\Bridge\Program.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.<Main>(String[] args)

</details>

**Comment by SzymonPobiega** [comment]
Hmmm I need to take a look at nsb raw...

**Comment by SzymonPobiega** [comment]
Can you check if you are using NSB.Raw beta3? It should contain the fix for this issue.

**Comment by SeanFeldman** [comment]
Working with all the recent changes introduced 🙂
